### ISSUE TITLE
Scons problem

### ISSUE THREAD

**Issue by panyz522** [tcz717/peetcode#1]
```shell
SCons import failed. Unable to find engine files in:
  /usr/local/bin/../engine
  /usr/local/bin/scons-local-3.0.1
  /usr/local/bin/scons-local
  /usr/local/lib/scons-3.0.1
  /usr/lib/scons-3.0.1
  /usr/local/lib/scons-3.0.1
  /usr/local/lib/python3.5/site-packages/scons-3.0.1
  /usr/lib/python3.5/site-packages/scons-3.0.1
  /usr/local/lib/python3.5/site-packages/scons-3.0.1
  /usr/lib/scons-3.0.1
  /usr/local/lib/scons
  /usr/lib/scons
  /usr/local/lib/scons
  /usr/local/lib/python3.5/site-packages/scons
  /usr/lib/python3.5/site-packages/scons
  /usr/local/lib/python3.5/site-packages/scons
  /usr/lib/scons
Traceback (most recent call last):
  File "/usr/local/bin/scons", line 192, in <module>
    import SCons.Script
ImportError: No module named 'SCons'
```

**Comment by tcz717** [comment]
You need to install python 3.6 and configuration the scons https://github.com/tcz717/peetcode#how-to-install

**Comment by panyz522** [comment]
```shell
SCons import failed. Unable to find engine files in:
  /usr/local/bin/../engine
  /usr/local/bin/scons-local-3.0.1
  /usr/local/bin/scons-local
  /usr/local/lib/scons-3.0.1
  /usr/lib/scons-3.0.1
  /usr/local/lib/scons-3.0.1
  /usr/local/lib/python3.6/site-packages/scons-3.0.1
  /usr/lib/python3.6/site-packages/scons-3.0.1
  /usr/local/lib/python3.6/site-packages/scons-3.0.1
  /usr/lib/scons-3.0.1
  /usr/local/lib/scons
  /usr/lib/scons
  /usr/local/lib/scons
  /usr/local/lib/python3.6/site-packages/scons
  /usr/lib/python3.6/site-packages/scons
  /usr/local/lib/python3.6/site-packages/scons
  /usr/lib/scons
Traceback (most recent call last):
  File "/usr/local/bin/scons", line 192, in <module>
    import SCons.Script
ModuleNotFoundError: No module named 'SCons'
```
same problem

**Comment by tcz717** [comment]
One temporary solution is to type `export PYTHONPATH=/usr/local/lib/python3.6/dist-packages/scons-3.0.1` before using `scons`
